export const sample_foods = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 20,
    favorite: false,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Poutine',
    price: 10,
    cookTime: '10-15',
    favorite: true,
    origins: ['Canada'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    price: 7,
    cookTime: '10-15',
    favorite: false,
    origins: ['Germany', 'US'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Shawarma',
    price: 10,
    cookTime: '5-10',
    favorite: true,
    origins: ['Persia', 'Middle East'],
    stars: 5,
    imageUrl: 'food-4.jpg',
    tags: ['FastFood',],
  },
  {
    id: '5',
    name: 'Chicken Soup',
    price: 8,
    cookTime: '40-50',
    favorite: false,
    origins: ['India', 'Asia'],
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'Fish and Chips',
    price: 9,
    cookTime: '10-15',
    favorite: false,
    origins: ['Portugal','British'],
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['FastFood', 'Lunch'],
  },
];